/**
 * sync-abi: copies packages/contracts/abi/*.json and packages/contracts/deployments/*.json into
 * src/generated/ as typed `as const` TS modules. Run automatically before dev/start/test.
 *
 * Missing files are tolerated (chain not deployed yet): the generated modules then carry
 * empty placeholders and the server degrades gracefully.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, basename } from 'node:path';

const ROOT = join(import.meta.dir, '..');
const ABI_DIR = process.env.PORTEX_ABI_DIR || join(ROOT, '..', '..', 'packages', 'contracts', 'abi');
const DEPLOY_DIR = join(ROOT, '..', '..', 'packages', 'contracts', 'deployments');
const OUT_DIR = join(ROOT, 'src', 'generated');
mkdirSync(OUT_DIR, { recursive: true });

function writeIfChanged(path: string, text: string): void {
  if (!existsSync(path) || readFileSync(path, 'utf8') !== text) writeFileSync(path, text);
}

const V31 = ['RaiseCore', 'ProjectTokenV31', 'GovernanceV31', 'VestingVaultV31', 'ClaimVault', 'TreasuryV31', 'RolloverRouterV31', 'RaiseFactoryV31', 'PortexRegistryV31', 'MockV4Adapter', 'MockUSDGV31', 'UniswapV4Adapter', 'PortexSwapRouterV31'];

const BANNER = '// AUTO-GENERATED by scripts/sync-abi.ts — do not edit.\n';

// ---- ABIs ----------------------------------------------------------------
const KNOWN = [
  'PortexRegistry', 'RaiseFactory', 'Raise', 'ProjectToken', 'Stage2Pool',
  'DiamondVault', 'AttestationBoard', 'SpendGovernor', 'IDexAdapter',
  'MockDexAdapter', 'MockUSDG',
] as const;

function exportName(contract: string): string {
  return `${contract}Abi`;
}

let abiOut = BANNER;
const present: string[] = [];
for (const name of KNOWN) {
  const file = join(ABI_DIR, `${name}.json`);
  let abi: unknown = [];
  if (existsSync(file)) {
    const parsed = JSON.parse(readFileSync(file, 'utf8'));
    abi = Array.isArray(parsed) ? parsed : (parsed.abi ?? []);
    if (Array.isArray(abi) && abi.length > 0) present.push(name);
  }
  abiOut += `export const ${exportName(name)} = ${JSON.stringify(abi)} as const;\n\n`;
}
// Extra ABI files not in KNOWN (forward-compatible, e.g. future contracts).
if (existsSync(ABI_DIR)) {
  for (const f of readdirSync(ABI_DIR).filter((f) => f.endsWith('.json')).sort()) {
    const name = basename(f, '.json');
    if ((KNOWN as readonly string[]).includes(name) || V31.includes(name)) continue;
    const parsed = JSON.parse(readFileSync(join(ABI_DIR, f), 'utf8'));
    const abi = Array.isArray(parsed) ? parsed : (parsed.abi ?? []);
    if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)) continue;
    abiOut += `export const ${exportName(name)} = ${JSON.stringify(abi)} as const;\n\n`;
    if (Array.isArray(abi) && abi.length > 0) present.push(name);
  }
}
abiOut += `export const hasGovernorAbi = ${present.includes('SpendGovernor')};\n`;
writeIfChanged(join(OUT_DIR, 'abis.ts'), abiOut);

// ---- deployments -----------------------------------------------------------
let depOut = BANNER;
depOut += 'export type Deployment = Record<string, string | number>;\n';
depOut += 'export const deployments: Record<string, Deployment> = {\n';
if (existsSync(DEPLOY_DIR)) {
  for (const f of readdirSync(DEPLOY_DIR).filter((f) => f.endsWith('.json')).sort()) {
    const chainId = basename(f, '.json');
    if (!/^\d+$/.test(chainId)) continue;
    const json = JSON.parse(readFileSync(join(DEPLOY_DIR, f), 'utf8'));
    depOut += `  ${JSON.stringify(chainId)}: ${JSON.stringify(json)},\n`;
  }
}
depOut += '} as const;\n';
writeIfChanged(join(OUT_DIR, 'deployments.ts'), depOut);

console.log(`sync-abi: ${present.length} ABIs (${present.join(', ') || 'none'}), deployments: ${existsSync(DEPLOY_DIR) ? readdirSync(DEPLOY_DIR).filter((f) => f.endsWith('.json')).join(', ') || 'none' : 'none'}`);

// Separate module: v1 imports remain byte-identical while its watch process is running.
let v31Out = BANNER;
for (const name of V31) {
  const file = join(ABI_DIR, `${name}.json`);
  if (!existsSync(file)) throw new Error(`Missing ${file}; run the dual deployment first`);
  const abi = JSON.parse(readFileSync(file, 'utf8'));
  v31Out += `export const ${name}Abi = ${JSON.stringify(abi)} as const;\n\n`;
}
writeIfChanged(join(OUT_DIR, 'v31-abis.ts'), v31Out);

console.log(`sync-abi v3.1: ${V31.length} ABIs (${V31.join(', ')})`);
