import RaiseCore from "@/generated/abi/RaiseCore.json";
import ProjectToken from "@/generated/abi/ProjectTokenV31.json";
import Governance from "@/generated/abi/GovernanceV31.json";
import Claims from "@/generated/abi/ClaimVault.json";
import Vesting from "@/generated/abi/VestingVaultV31.json";
import Factory from "@/generated/abi/RaiseFactoryV31.json";
import Registry from "@/generated/abi/PortexRegistryV31.json";
import Quote from "@/generated/abi/MockUSDGV31.json";
import Treasury from "@/generated/abi/TreasuryV31.json";
import Router from "@/generated/abi/RolloverRouterV31.json";
import type { Abi } from "viem";
export const raiseAbi = RaiseCore as Abi;
export const tokenAbi = ProjectToken as Abi;
export const governanceAbi = Governance as Abi;
export const claimsAbi = Claims as Abi;
export const vestingAbi = Vesting as Abi;
export const raiseFactoryAbi = Factory as Abi;
export const registryAbi = Registry as Abi;
export const erc20Abi = Quote as Abi;
export const treasuryAbi = Treasury as Abi;
export const routerAbi = Router as Abi;
